spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://portfoliodb.c29jzg47agm4.ap-northeast-2.rds.amazonaws.com:3306/portfoliodb
    username: admin
    password: 1q2w3e4r
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 588031225464-krfbhh2d0r03ftktqhjq0ubhmgthjlpr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations:
    - /mappers/*.xml

jwt:
  secret: ezV2FMXHX7bzV8eEL9lHf0MLSCnB5M6gtjcHmokIxABqjplbHtRypoN8H2vMTxVO
